[project]
name = "mini-project1-hr-resume-goodfit-or-not"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Urja Jain", email = "jainurja72@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "pypdf>=6.16.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
mini-project1-hr-resume-goodfit-or-not = "mini_project1_hr_resume_goodfit_or_not:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
